# Generated by Django 5.2.6 on 2025-10-01 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rari', '0003_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='craft',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
